name: Test and Publish Coder Templates

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
  workflow_dispatch:
    inputs:
      template:
        description: 'Template to publish (leave empty for all changed templates)'
        required: false
        type: choice
        options:
          - ''
          - docker
          - git-setup

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-publish:
    name: Test and Publish - ${{ matrix.template }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        template: [docker, git-setup]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for template changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docker:
              - 'templates/docker/**'
            git-setup:
              - 'templates/git-setup/**'

      - name: Determine if job should run
        id: should_run
        run: |
          # Check if this specific template changed
          if [[ "${{ matrix.template }}" == "docker" ]]; then
            CHANGED="${{ steps.filter.outputs.docker }}"
          else
            CHANGED="${{ steps.filter.outputs.git-setup }}"
          fi

          # Skip if:
          # - Push event and this template hasn't changed
          # - Manual trigger with specific template that doesn't match this one
          if [[ "${{ github.event_name }}" == "push" && "$CHANGED" != "true" ]]; then
            echo "Skipping - no changes detected for ${{ matrix.template }}"
            echo "skip=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.template }}" && "${{ github.event.inputs.template }}" != "${{ matrix.template }}" ]]; then
            echo "Skipping - manual trigger for different template"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Running workflow for ${{ matrix.template }}"
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Terraform
        if: steps.should_run.outputs.skip != 'true'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Set up Coder CLI
        if: steps.should_run.outputs.skip != 'true'
        uses: coder/setup-action@v1
        with:
          access_url: "https://coder.balancefriends.com"
          coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}

      - name: Validate Terraform template
        if: steps.should_run.outputs.skip != 'true'
        run: terraform validate
        working-directory: ./templates/${{ matrix.template }}

      - name: Get short commit SHA to use as template version name
        if: steps.should_run.outputs.skip != 'true'
        id: name
        run: echo "version_name=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Get latest commit title to use as template version description
        if: steps.should_run.outputs.skip != 'true'
        id: message
        run: echo "pr_title=$(git log --format=%s -n 1 ${{ github.sha }})" >> "$GITHUB_OUTPUT"

      - name: Push template to Coder
        if: steps.should_run.outputs.skip != 'true'
        run: |
          coder templates push ${{ matrix.template }} \
            --activate=false \
            --name ${{ steps.name.outputs.version_name }} \
            --message "${{ steps.message.outputs.pr_title }}" \
            --yes
        working-directory: ./templates/${{ matrix.template }}

      #- name: Create a test workspace and run some example commands
      #  run: |
      #    coder create -t ${{ matrix.template }} \
      #      --template-version ${{ steps.name.outputs.version_name }} \
      #      test-${{ matrix.template }}-${{ steps.name.outputs.version_name }} \
      #      --yes
      #    # run some example commands
      #    coder ssh test-${{ matrix.template }}-${{ steps.name.outputs.version_name }} -- echo "Test passed"
      #  working-directory: ./templates/${{ matrix.template }}

      - name: Delete the test workspace
        if: always() && steps.should_run.outputs.skip != 'true'
        run: coder delete test-${{ matrix.template }}-${{ steps.name.outputs.version_name }} --yes
        continue-on-error: true

      - name: Promote template version
        if: success() && steps.should_run.outputs.skip != 'true'
        run: |
          coder template version promote \
            --template=${{ matrix.template }} \
            --template-version=${{ steps.name.outputs.version_name }} \
            --yes
